// GENERATED by tools/gen_tiles.py -- do not edit by hand.
import Toybox.Application;
import Toybox.Lang;

module TileIndex {
    const LAT0 = 33.900000;       // SW origin of the tile grid
    const LON0 = -119.950000;
    const TILE_DEG = 0.05;
    const HOME_LAT = 34.200000;         // centre of the generated data
    const HOME_LON = -119.150000;

    // "ix_iy" -> JSON resource id for every populated tile.
    var mSyms = {
        "0_3" => Rez.JsonData.Tile_0_3,
        "1_1" => Rez.JsonData.Tile_1_1,
        "1_2" => Rez.JsonData.Tile_1_2,
        "1_3" => Rez.JsonData.Tile_1_3,
        "1_10" => Rez.JsonData.Tile_1_10,
        "1_11" => Rez.JsonData.Tile_1_11,
        "2_0" => Rez.JsonData.Tile_2_0,
        "2_1" => Rez.JsonData.Tile_2_1,
        "2_3" => Rez.JsonData.Tile_2_3,
        "2_10" => Rez.JsonData.Tile_2_10,
        "2_11" => Rez.JsonData.Tile_2_11,
        "3_1" => Rez.JsonData.Tile_3_1,
        "3_3" => Rez.JsonData.Tile_3_3,
        "3_10" => Rez.JsonData.Tile_3_10,
        "3_11" => Rez.JsonData.Tile_3_11,
        "4_1" => Rez.JsonData.Tile_4_1,
        "4_2" => Rez.JsonData.Tile_4_2,
        "4_3" => Rez.JsonData.Tile_4_3,
        "4_9" => Rez.JsonData.Tile_4_9,
        "4_10" => Rez.JsonData.Tile_4_10,
        "4_11" => Rez.JsonData.Tile_4_11,
        "5_1" => Rez.JsonData.Tile_5_1,
        "5_2" => Rez.JsonData.Tile_5_2,
        "5_10" => Rez.JsonData.Tile_5_10,
        "5_11" => Rez.JsonData.Tile_5_11,
        "6_1" => Rez.JsonData.Tile_6_1,
        "6_2" => Rez.JsonData.Tile_6_2,
        "6_10" => Rez.JsonData.Tile_6_10,
        "6_11" => Rez.JsonData.Tile_6_11,
        "7_1" => Rez.JsonData.Tile_7_1,
        "7_2" => Rez.JsonData.Tile_7_2,
        "7_3" => Rez.JsonData.Tile_7_3,
        "7_10" => Rez.JsonData.Tile_7_10,
        "8_2" => Rez.JsonData.Tile_8_2,
        "8_9" => Rez.JsonData.Tile_8_9,
        "8_10" => Rez.JsonData.Tile_8_10,
        "8_11" => Rez.JsonData.Tile_8_11,
        "9_9" => Rez.JsonData.Tile_9_9,
        "9_10" => Rez.JsonData.Tile_9_10,
        "10_2" => Rez.JsonData.Tile_10_2,
        "10_8" => Rez.JsonData.Tile_10_8,
        "10_9" => Rez.JsonData.Tile_10_9,
        "10_10" => Rez.JsonData.Tile_10_10,
        "11_2" => Rez.JsonData.Tile_11_2,
        "11_8" => Rez.JsonData.Tile_11_8,
        "11_9" => Rez.JsonData.Tile_11_9,
        "11_10" => Rez.JsonData.Tile_11_10,
        "12_7" => Rez.JsonData.Tile_12_7,
        "12_8" => Rez.JsonData.Tile_12_8,
        "12_9" => Rez.JsonData.Tile_12_9,
        "12_10" => Rez.JsonData.Tile_12_10,
        "12_11" => Rez.JsonData.Tile_12_11,
        "13_6" => Rez.JsonData.Tile_13_6,
        "13_7" => Rez.JsonData.Tile_13_7,
        "13_8" => Rez.JsonData.Tile_13_8,
        "13_9" => Rez.JsonData.Tile_13_9,
        "13_10" => Rez.JsonData.Tile_13_10,
        "13_11" => Rez.JsonData.Tile_13_11,
        "14_4" => Rez.JsonData.Tile_14_4,
        "14_5" => Rez.JsonData.Tile_14_5,
        "14_6" => Rez.JsonData.Tile_14_6,
        "14_7" => Rez.JsonData.Tile_14_7,
        "14_8" => Rez.JsonData.Tile_14_8,
        "14_10" => Rez.JsonData.Tile_14_10,
        "14_11" => Rez.JsonData.Tile_14_11,
        "15_4" => Rez.JsonData.Tile_15_4,
        "15_5" => Rez.JsonData.Tile_15_5,
        "15_6" => Rez.JsonData.Tile_15_6,
        "15_7" => Rez.JsonData.Tile_15_7,
        "15_8" => Rez.JsonData.Tile_15_8,
        "15_9" => Rez.JsonData.Tile_15_9,
        "15_10" => Rez.JsonData.Tile_15_10,
        "16_3" => Rez.JsonData.Tile_16_3,
        "16_4" => Rez.JsonData.Tile_16_4,
        "16_5" => Rez.JsonData.Tile_16_5,
        "16_6" => Rez.JsonData.Tile_16_6,
        "16_7" => Rez.JsonData.Tile_16_7,
        "16_8" => Rez.JsonData.Tile_16_8,
        "16_9" => Rez.JsonData.Tile_16_9,
        "16_10" => Rez.JsonData.Tile_16_10,
        "16_11" => Rez.JsonData.Tile_16_11,
        "17_3" => Rez.JsonData.Tile_17_3,
        "17_4" => Rez.JsonData.Tile_17_4,
        "17_5" => Rez.JsonData.Tile_17_5,
        "17_6" => Rez.JsonData.Tile_17_6,
        "17_7" => Rez.JsonData.Tile_17_7,
        "17_8" => Rez.JsonData.Tile_17_8,
        "17_9" => Rez.JsonData.Tile_17_9,
        "17_10" => Rez.JsonData.Tile_17_10,
        "18_3" => Rez.JsonData.Tile_18_3,
        "18_4" => Rez.JsonData.Tile_18_4,
        "18_5" => Rez.JsonData.Tile_18_5,
        "18_6" => Rez.JsonData.Tile_18_6,
        "18_7" => Rez.JsonData.Tile_18_7,
        "18_8" => Rez.JsonData.Tile_18_8,
        "18_9" => Rez.JsonData.Tile_18_9,
        "19_2" => Rez.JsonData.Tile_19_2,
        "19_3" => Rez.JsonData.Tile_19_3,
        "19_4" => Rez.JsonData.Tile_19_4,
        "19_5" => Rez.JsonData.Tile_19_5,
        "19_6" => Rez.JsonData.Tile_19_6,
        "19_7" => Rez.JsonData.Tile_19_7,
        "19_8" => Rez.JsonData.Tile_19_8,
        "19_9" => Rez.JsonData.Tile_19_9,
        "19_10" => Rez.JsonData.Tile_19_10,
        "20_2" => Rez.JsonData.Tile_20_2,
        "20_3" => Rez.JsonData.Tile_20_3,
        "20_4" => Rez.JsonData.Tile_20_4,
        "20_5" => Rez.JsonData.Tile_20_5,
        "20_6" => Rez.JsonData.Tile_20_6,
        "20_7" => Rez.JsonData.Tile_20_7,
        "20_8" => Rez.JsonData.Tile_20_8,
        "20_9" => Rez.JsonData.Tile_20_9,
        "20_10" => Rez.JsonData.Tile_20_10,
        "20_11" => Rez.JsonData.Tile_20_11,
        "21_2" => Rez.JsonData.Tile_21_2,
        "21_3" => Rez.JsonData.Tile_21_3,
        "21_4" => Rez.JsonData.Tile_21_4,
        "21_5" => Rez.JsonData.Tile_21_5,
        "21_6" => Rez.JsonData.Tile_21_6,
        "21_7" => Rez.JsonData.Tile_21_7,
        "21_8" => Rez.JsonData.Tile_21_8,
        "21_9" => Rez.JsonData.Tile_21_9,
        "21_10" => Rez.JsonData.Tile_21_10,
        "22_2" => Rez.JsonData.Tile_22_2,
        "22_3" => Rez.JsonData.Tile_22_3,
        "22_4" => Rez.JsonData.Tile_22_4,
        "22_5" => Rez.JsonData.Tile_22_5,
        "22_6" => Rez.JsonData.Tile_22_6,
        "22_7" => Rez.JsonData.Tile_22_7,
        "22_9" => Rez.JsonData.Tile_22_9,
        "22_10" => Rez.JsonData.Tile_22_10,
        "23_2" => Rez.JsonData.Tile_23_2,
        "23_4" => Rez.JsonData.Tile_23_4,
        "23_5" => Rez.JsonData.Tile_23_5,
        "23_7" => Rez.JsonData.Tile_23_7,
        "23_9" => Rez.JsonData.Tile_23_9,
        "23_10" => Rez.JsonData.Tile_23_10,
        "23_11" => Rez.JsonData.Tile_23_11,
        "24_2" => Rez.JsonData.Tile_24_2,
        "24_3" => Rez.JsonData.Tile_24_3,
        "24_4" => Rez.JsonData.Tile_24_4,
        "24_5" => Rez.JsonData.Tile_24_5,
        "24_6" => Rez.JsonData.Tile_24_6,
        "24_7" => Rez.JsonData.Tile_24_7,
        "24_8" => Rez.JsonData.Tile_24_8,
        "24_9" => Rez.JsonData.Tile_24_9,
        "24_10" => Rez.JsonData.Tile_24_10,
        "24_11" => Rez.JsonData.Tile_24_11,
        "25_2" => Rez.JsonData.Tile_25_2,
        "25_3" => Rez.JsonData.Tile_25_3,
        "25_4" => Rez.JsonData.Tile_25_4,
        "25_5" => Rez.JsonData.Tile_25_5,
        "25_6" => Rez.JsonData.Tile_25_6,
        "25_7" => Rez.JsonData.Tile_25_7,
        "25_10" => Rez.JsonData.Tile_25_10,
        "26_2" => Rez.JsonData.Tile_26_2,
        "26_4" => Rez.JsonData.Tile_26_4,
        "26_5" => Rez.JsonData.Tile_26_5,
        "26_6" => Rez.JsonData.Tile_26_6,
        "26_7" => Rez.JsonData.Tile_26_7,
        "26_9" => Rez.JsonData.Tile_26_9,
        "26_10" => Rez.JsonData.Tile_26_10,
        "26_11" => Rez.JsonData.Tile_26_11,
        "27_2" => Rez.JsonData.Tile_27_2,
        "27_3" => Rez.JsonData.Tile_27_3,
        "27_5" => Rez.JsonData.Tile_27_5,
        "27_6" => Rez.JsonData.Tile_27_6,
        "27_7" => Rez.JsonData.Tile_27_7,
        "27_8" => Rez.JsonData.Tile_27_8,
        "27_9" => Rez.JsonData.Tile_27_9,
        "27_10" => Rez.JsonData.Tile_27_10,
        "27_11" => Rez.JsonData.Tile_27_11,
        "28_5" => Rez.JsonData.Tile_28_5,
        "28_10" => Rez.JsonData.Tile_28_10,
        "29_5" => Rez.JsonData.Tile_29_5,
        "29_10" => Rez.JsonData.Tile_29_10,
        "30_10" => Rez.JsonData.Tile_30_10,
        "31_10" => Rez.JsonData.Tile_31_10,
    };

    function floorDiv(v as Float) as Number {
        var n = v.toNumber();              // truncates toward zero
        if (v < 0.0 && v.toFloat() != n) {
            n -= 1;
        }
        return n;
    }

    function tileX(lon as Float) as Number {
        return floorDiv((lon - LON0) / TILE_DEG);
    }

    function tileY(lat as Float) as Number {
        return floorDiv((lat - LAT0) / TILE_DEG);
    }

    // Loads and parses a tile, or returns null if that tile has no data.
    function load(ix as Number, iy as Number) {
        var sym = mSyms[ix + "_" + iy];
        if (sym == null) {
            return null;
        }
        return Application.loadResource(sym);
    }

    // The whole-region overview layer (shown when zoomed out).
    function loadOverview() {
        return Application.loadResource(Rez.JsonData.Overview);
    }
}
