// GENERATED by tools/gen_tiles.py -- do not edit by hand.
import Toybox.Application;
import Toybox.Lang;

module TileIndex {
    const LAT0 = -90.000000;       // SW origin of the tile grid
    const LON0 = -180.000000;
    const TILE_DEG = 0.05;
    const HOME_LAT = 34.225000;         // centre of the generated data
    const HOME_LON = -119.275000;

    // "ix_iy" -> JSON resource id for every populated tile.
    var mSyms = {
        "1200_2488" => Rez.JsonData.Tile_1200_2488,
        "1200_2489" => Rez.JsonData.Tile_1200_2489,
        "1201_2481" => Rez.JsonData.Tile_1201_2481,
        "1201_2488" => Rez.JsonData.Tile_1201_2488,
        "1201_2489" => Rez.JsonData.Tile_1201_2489,
        "1202_2479" => Rez.JsonData.Tile_1202_2479,
        "1202_2480" => Rez.JsonData.Tile_1202_2480,
        "1202_2481" => Rez.JsonData.Tile_1202_2481,
        "1202_2488" => Rez.JsonData.Tile_1202_2488,
        "1202_2489" => Rez.JsonData.Tile_1202_2489,
        "1203_2478" => Rez.JsonData.Tile_1203_2478,
        "1203_2479" => Rez.JsonData.Tile_1203_2479,
        "1203_2481" => Rez.JsonData.Tile_1203_2481,
        "1203_2488" => Rez.JsonData.Tile_1203_2488,
        "1203_2489" => Rez.JsonData.Tile_1203_2489,
        "1204_2479" => Rez.JsonData.Tile_1204_2479,
        "1204_2481" => Rez.JsonData.Tile_1204_2481,
        "1204_2488" => Rez.JsonData.Tile_1204_2488,
        "1204_2489" => Rez.JsonData.Tile_1204_2489,
        "1205_2479" => Rez.JsonData.Tile_1205_2479,
        "1205_2480" => Rez.JsonData.Tile_1205_2480,
        "1205_2481" => Rez.JsonData.Tile_1205_2481,
        "1205_2487" => Rez.JsonData.Tile_1205_2487,
        "1205_2488" => Rez.JsonData.Tile_1205_2488,
        "1205_2489" => Rez.JsonData.Tile_1205_2489,
        "1206_2479" => Rez.JsonData.Tile_1206_2479,
        "1206_2480" => Rez.JsonData.Tile_1206_2480,
        "1206_2488" => Rez.JsonData.Tile_1206_2488,
        "1207_2479" => Rez.JsonData.Tile_1207_2479,
        "1207_2480" => Rez.JsonData.Tile_1207_2480,
        "1207_2488" => Rez.JsonData.Tile_1207_2488,
        "1207_2489" => Rez.JsonData.Tile_1207_2489,
        "1208_2479" => Rez.JsonData.Tile_1208_2479,
        "1208_2480" => Rez.JsonData.Tile_1208_2480,
        "1208_2481" => Rez.JsonData.Tile_1208_2481,
        "1208_2488" => Rez.JsonData.Tile_1208_2488,
        "1208_2489" => Rez.JsonData.Tile_1208_2489,
        "1208_2490" => Rez.JsonData.Tile_1208_2490,
        "1209_2480" => Rez.JsonData.Tile_1209_2480,
        "1209_2487" => Rez.JsonData.Tile_1209_2487,
        "1209_2488" => Rez.JsonData.Tile_1209_2488,
        "1209_2489" => Rez.JsonData.Tile_1209_2489,
        "1210_2487" => Rez.JsonData.Tile_1210_2487,
        "1210_2488" => Rez.JsonData.Tile_1210_2488,
        "1210_2489" => Rez.JsonData.Tile_1210_2489,
        "1211_2480" => Rez.JsonData.Tile_1211_2480,
        "1211_2486" => Rez.JsonData.Tile_1211_2486,
        "1211_2487" => Rez.JsonData.Tile_1211_2487,
        "1212_2480" => Rez.JsonData.Tile_1212_2480,
        "1212_2486" => Rez.JsonData.Tile_1212_2486,
        "1212_2487" => Rez.JsonData.Tile_1212_2487,
        "1212_2488" => Rez.JsonData.Tile_1212_2488,
        "1213_2485" => Rez.JsonData.Tile_1213_2485,
        "1213_2486" => Rez.JsonData.Tile_1213_2486,
        "1213_2487" => Rez.JsonData.Tile_1213_2487,
        "1213_2488" => Rez.JsonData.Tile_1213_2488,
        "1213_2489" => Rez.JsonData.Tile_1213_2489,
        "1214_2484" => Rez.JsonData.Tile_1214_2484,
        "1214_2485" => Rez.JsonData.Tile_1214_2485,
        "1214_2486" => Rez.JsonData.Tile_1214_2486,
        "1214_2488" => Rez.JsonData.Tile_1214_2488,
        "1214_2489" => Rez.JsonData.Tile_1214_2489,
        "1215_2482" => Rez.JsonData.Tile_1215_2482,
        "1215_2483" => Rez.JsonData.Tile_1215_2483,
        "1215_2484" => Rez.JsonData.Tile_1215_2484,
        "1215_2485" => Rez.JsonData.Tile_1215_2485,
        "1215_2486" => Rez.JsonData.Tile_1215_2486,
        "1215_2488" => Rez.JsonData.Tile_1215_2488,
        "1215_2489" => Rez.JsonData.Tile_1215_2489,
        "1216_2482" => Rez.JsonData.Tile_1216_2482,
        "1216_2483" => Rez.JsonData.Tile_1216_2483,
        "1216_2484" => Rez.JsonData.Tile_1216_2484,
        "1216_2485" => Rez.JsonData.Tile_1216_2485,
        "1216_2486" => Rez.JsonData.Tile_1216_2486,
        "1216_2487" => Rez.JsonData.Tile_1216_2487,
        "1216_2488" => Rez.JsonData.Tile_1216_2488,
        "1216_2489" => Rez.JsonData.Tile_1216_2489,
        "1217_2481" => Rez.JsonData.Tile_1217_2481,
        "1217_2482" => Rez.JsonData.Tile_1217_2482,
        "1217_2483" => Rez.JsonData.Tile_1217_2483,
        "1217_2484" => Rez.JsonData.Tile_1217_2484,
        "1217_2485" => Rez.JsonData.Tile_1217_2485,
        "1217_2486" => Rez.JsonData.Tile_1217_2486,
        "1217_2487" => Rez.JsonData.Tile_1217_2487,
        "1218_2481" => Rez.JsonData.Tile_1218_2481,
        "1218_2482" => Rez.JsonData.Tile_1218_2482,
        "1218_2483" => Rez.JsonData.Tile_1218_2483,
        "1218_2484" => Rez.JsonData.Tile_1218_2484,
        "1218_2485" => Rez.JsonData.Tile_1218_2485,
        "1218_2486" => Rez.JsonData.Tile_1218_2486,
        "1218_2487" => Rez.JsonData.Tile_1218_2487,
        "1219_2481" => Rez.JsonData.Tile_1219_2481,
        "1219_2482" => Rez.JsonData.Tile_1219_2482,
        "1219_2483" => Rez.JsonData.Tile_1219_2483,
        "1219_2484" => Rez.JsonData.Tile_1219_2484,
        "1219_2485" => Rez.JsonData.Tile_1219_2485,
        "1219_2486" => Rez.JsonData.Tile_1219_2486,
        "1219_2487" => Rez.JsonData.Tile_1219_2487,
        "1220_2480" => Rez.JsonData.Tile_1220_2480,
        "1220_2481" => Rez.JsonData.Tile_1220_2481,
        "1220_2483" => Rez.JsonData.Tile_1220_2483,
        "1220_2484" => Rez.JsonData.Tile_1220_2484,
        "1220_2485" => Rez.JsonData.Tile_1220_2485,
        "1220_2487" => Rez.JsonData.Tile_1220_2487,
        "1221_2480" => Rez.JsonData.Tile_1221_2480,
        "1221_2481" => Rez.JsonData.Tile_1221_2481,
        "1221_2483" => Rez.JsonData.Tile_1221_2483,
        "1221_2484" => Rez.JsonData.Tile_1221_2484,
        "1221_2485" => Rez.JsonData.Tile_1221_2485,
        "1221_2486" => Rez.JsonData.Tile_1221_2486,
        "1221_2487" => Rez.JsonData.Tile_1221_2487,
        "1222_2480" => Rez.JsonData.Tile_1222_2480,
        "1222_2481" => Rez.JsonData.Tile_1222_2481,
        "1222_2482" => Rez.JsonData.Tile_1222_2482,
        "1222_2483" => Rez.JsonData.Tile_1222_2483,
        "1222_2484" => Rez.JsonData.Tile_1222_2484,
        "1222_2485" => Rez.JsonData.Tile_1222_2485,
        "1222_2486" => Rez.JsonData.Tile_1222_2486,
        "1222_2487" => Rez.JsonData.Tile_1222_2487,
        "1223_2480" => Rez.JsonData.Tile_1223_2480,
        "1223_2481" => Rez.JsonData.Tile_1223_2481,
        "1223_2482" => Rez.JsonData.Tile_1223_2482,
        "1223_2483" => Rez.JsonData.Tile_1223_2483,
        "1223_2484" => Rez.JsonData.Tile_1223_2484,
        "1223_2485" => Rez.JsonData.Tile_1223_2485,
        "1223_2487" => Rez.JsonData.Tile_1223_2487,
        "1223_2488" => Rez.JsonData.Tile_1223_2488,
        "1224_2480" => Rez.JsonData.Tile_1224_2480,
        "1224_2482" => Rez.JsonData.Tile_1224_2482,
        "1224_2483" => Rez.JsonData.Tile_1224_2483,
        "1224_2485" => Rez.JsonData.Tile_1224_2485,
        "1224_2487" => Rez.JsonData.Tile_1224_2487,
        "1224_2488" => Rez.JsonData.Tile_1224_2488,
        "1224_2489" => Rez.JsonData.Tile_1224_2489,
        "1225_2480" => Rez.JsonData.Tile_1225_2480,
        "1225_2481" => Rez.JsonData.Tile_1225_2481,
        "1225_2482" => Rez.JsonData.Tile_1225_2482,
        "1225_2483" => Rez.JsonData.Tile_1225_2483,
        "1225_2484" => Rez.JsonData.Tile_1225_2484,
        "1225_2485" => Rez.JsonData.Tile_1225_2485,
        "1225_2486" => Rez.JsonData.Tile_1225_2486,
        "1225_2487" => Rez.JsonData.Tile_1225_2487,
        "1225_2488" => Rez.JsonData.Tile_1225_2488,
        "1225_2489" => Rez.JsonData.Tile_1225_2489,
        "1226_2480" => Rez.JsonData.Tile_1226_2480,
        "1226_2482" => Rez.JsonData.Tile_1226_2482,
        "1226_2483" => Rez.JsonData.Tile_1226_2483,
        "1226_2484" => Rez.JsonData.Tile_1226_2484,
        "1226_2485" => Rez.JsonData.Tile_1226_2485,
        "1226_2488" => Rez.JsonData.Tile_1226_2488,
        "1226_2490" => Rez.JsonData.Tile_1226_2490,
        "1227_2480" => Rez.JsonData.Tile_1227_2480,
        "1227_2482" => Rez.JsonData.Tile_1227_2482,
        "1227_2483" => Rez.JsonData.Tile_1227_2483,
        "1227_2484" => Rez.JsonData.Tile_1227_2484,
        "1227_2485" => Rez.JsonData.Tile_1227_2485,
        "1227_2488" => Rez.JsonData.Tile_1227_2488,
        "1227_2489" => Rez.JsonData.Tile_1227_2489,
        "1227_2490" => Rez.JsonData.Tile_1227_2490,
        "1228_2480" => Rez.JsonData.Tile_1228_2480,
        "1228_2483" => Rez.JsonData.Tile_1228_2483,
        "1228_2484" => Rez.JsonData.Tile_1228_2484,
        "1228_2485" => Rez.JsonData.Tile_1228_2485,
        "1228_2488" => Rez.JsonData.Tile_1228_2488,
        "1228_2489" => Rez.JsonData.Tile_1228_2489,
    };

    function floorDiv(v as Float) as Number {
        var n = v.toNumber();              // truncates toward zero
        if (v < 0.0 && v.toFloat() != n) {
            n -= 1;
        }
        return n;
    }

    function tileX(lon as Float) as Number {
        return floorDiv((lon - LON0) / TILE_DEG);
    }

    function tileY(lat as Float) as Number {
        return floorDiv((lat - LAT0) / TILE_DEG);
    }

    // Loads and parses a tile, or returns null if that tile has no data.
    function load(ix as Number, iy as Number) {
        var sym = mSyms[ix + "_" + iy];
        if (sym == null) {
            return null;
        }
        return Application.loadResource(sym);
    }

    // The whole-region overview layer (shown when zoomed out).
    function loadOverview() {
        return Application.loadResource(Rez.JsonData.Overview);
    }
}
